### ISSUE TITLE
 FieldUtils.writeStaticField(cls, "gDefault", new android.util.Singleton<Object>() 

### ISSUE THREAD

**Issue by dssljt** [Qihoo360/DroidPlugin#1]
Error:(91, 74) 错误: 找不到符号
符号:   类 Singleton
位置: 程序包 android.util

找不到这个Singleton<Object> 报错 为什么呢

**Comment by bjzhou** [comment]
查看了下源码，Singleton类属于隐藏API，不能直接调用，简单的解决办法是在DroidPlugin里新建包android.util，然后把Singleton.java丢进去

```java
package android.util;

/**
 * Singleton helper class for lazily initialization.
 *
 * Modeled after frameworks/base/include/utils/Singleton.h
 *
 * @hide
 */
public abstract class Singleton<T> {
    private T mInstance;

    protected abstract T create();

    public final T get() {
        synchronized (this) {
            if (mInstance == null) {
                mInstance = create();
            }
            return mInstance;
        }
    }
}
```

**Comment by a6511631** [comment]
Droid Plugin的library中，IPluginManager中关于以下的引用会提示can't find import class，如下图。
![image](https://cloud.githubusercontent.com/assets/10797268/9560315/c629b8a6-4e3f-11e5-93f0-659c8e5b02da.png)
网上的资料提出要去修改framework层的frameworks/base/Android.mk。除此之外，您能否给一点帮助呢

**Comment by qihoo360github** [comment]
@bjzhou 这样不行的，在部分手机上会导致插件无法运行的。

**Comment by aoqianglin** [comment]
@qihoo360github 那该怎么处理

**Comment by cmzy** [comment]
@aoqianglin 我稍后会提交代码处理下吧

**Comment by dustookk** [comment]
@cmzy 你直接new android.util.Singleton这么写没有报红吗?  


这种hide的代码如果可以这么写就太好了, 求方法 :+1:

**Comment by qihoo360github** [comment]
@dustookk 等我重新提交吧。

**Comment by markzhai** [comment]
好像还没解决这个问题？

**Comment by openproject** [comment]
同问，等答复

**Comment by 116205035** [comment]
http://www.cnblogs.com/wanqieddy/archive/2013/05/24/3096312.html
看来需要打包一个非阉割版的 android.jar  这样才能调用隐藏的api
直接把编译后的jar 提交上来也可以？

**Comment by binglingziyu** [comment]
快点解决吧，我正想试试呢

**Comment by dustookk** [comment]
这个问题先这么解决:

生成一个只有android.util.Singleton的jar包导入项目中.  但是不要输出到生成的apk.

就行了.

**Comment by cmzy** [comment]
fixed and close

**Comment by cmzy** [comment]
fixed and close

**Comment by whatl** [comment]
把Hook.java mEnable改为true，就可以运行了
