### ISSUE TITLE
E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription'

### ISSUE THREAD

**Issue by DavidYes** [Qihoo360/DroidPlugin#100]
最近版本运行的时候，发现会出这样的问题，导致子应用加载后就自动退出了～求指教！

12-14 20:03:57.372 9859-9859/com.micsoft.tv W/dalvikvm: VFY: unable to resolve virtual method 61: Landroid/app/Activity;.getCodeCacheDir ()Ljava/io/File;
12-14 20:03:57.372 9859-9859/com.micsoft.tv D/dalvikvm: VFY: replacing opcode 0x6f at 0x02f8
12-14 20:03:57.374 9859-9859/com.micsoft.tv E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.micsoft.tv.HistoryActivity.access$super
12-14 20:03:57.374 9859-9859/com.micsoft.tv W/dalvikvm: VFY: unable to resolve check-cast 12 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/micsoft/tv/HistoryActivity;
12-14 20:03:57.374 9859-9859/com.micsoft.tv D/dalvikvm: VFY: replacing opcode 0x1f at 0x04d4
12-14 20:03:57.375 9859-9859/com.micsoft.tv I/dalvikvm: Could not find method android.app.Activity.postponeEnterTransition, referenced from method com.micsoft.tv.HistoryActivity.access$super
12-14 20:03:57.375 9859-9859/com.micsoft.tv W/dalvikvm: VFY: unable to resolve virtual method 217: Landroid/app/Activity;.postponeEnterTransition ()V

**Comment by Wmmeng** [comment]
我也碰到这个问题了：应用从recent task中被干掉后，再点击Icon就会有这个bug，第二次点击的时候就可以正常启动。@DavidYes 解决没？

**Comment by DavidYes** [comment]
解决了，部分机型这个api没有开放，直接用反射的方式调用。你看看有什么问题：
我现在发现比较棘手的几件事情：
1，在 锤子 手机上hook webview的时候，必然散退；
2，startactivity的时候，addFlag无效，比如 intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

intent.addFlags(Intent.FLAG_ACTIVITY_NO_USER_ACTION);

之前非动态加载的版本都可以正常使用，但是引入droidplugin后这些flag就失效，
对应intent传值，比如 public Intent putExtra(String name, Serializable value) 
无法正常传递 序列化的对象到相应的activity;


 private void fixTaskDescription(Activity activity, ActivityInfo targetInfo) {
        Log.e(TAG, "PluginInstrumentation.fixTaskDescription() Build.VERSION.SDK_INT:", Build.VERSION.SDK_INT);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            PackageManager pm = mHostContext.getPackageManager();
            String lablel = String.valueOf(targetInfo.loadLabel(pm));
            Drawable icon = targetInfo.loadIcon(pm);
            Bitmap bitmap = null;
            if (icon instanceof BitmapDrawable) {
                bitmap = ((BitmapDrawable) icon).getBitmap();
            }
/*            if (bitmap != null) {
                activity.setTaskDescription(new android.app.ActivityManager.TaskDescription(lablel, bitmap));
            } else {
                activity.setTaskDescription(new android.app.ActivityManager.TaskDescription(lablel));
            }*/

            // The legacy method call
            // setTaskDescription(new ActivityManager.TaskDescription(title, icon, color));

            // The reflected method call
            try {
                Class<?> clazz = Class.forName("android.app.ActivityManager$TaskDescription");
                Constructor<?> cons = clazz.getConstructor(String.class, Bitmap.class, int.class);
//                Object taskDescription = cons.newInstance(lablel, icon);
                Object taskDescription;
                if (bitmap != null) {
                    taskDescription = cons.newInstance(lablel, bitmap);
                } else {
                    taskDescription = cons.newInstance(lablel);
                }

                Method method = ((Object) activity).getClass().getMethod("setTaskDescription", clazz);
                method.invoke(activity, taskDescription); //this is your Activity instance
            } catch (Exception e) {
                // Log this :)
            }
        }
    }

**Comment by cmzy** [comment]
fixed
