### ISSUE TITLE
导入工程运行报错，我看了一一下，没有重复的provider啊

### ISSUE THREAD

**Issue by foreverxiongtao** [Qihoo360/DroidPlugin#102]
pkg: /data/local/tmp/com.example.TestPlugin
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]

**Comment by tianqiujie** [comment]
+1

**Comment by tianqiujie** [comment]
解决了 卸载掉360手机助手...

**Comment by Wmmeng** [comment]
这个是因为360手机助手和插件库的provider的authority冲突的原因。在Library中的manifest所有的provider的authority都替换成你自己的包名就行了。

**Comment by pandaApe** [comment]
@Wmmeng  按照你的方法已解决问题。这个算是bug么？所有的都改多麻烦

**Comment by codehz** [comment]
我建议提供一个工具批量修改——这个做成脚本应该不复杂的

**Comment by cmzy** [comment]
closed
