### ISSUE TITLE
部分机型动态加载闪退：Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.

### ISSUE THREAD

**Issue by DavidYes** [Qihoo360/DroidPlugin#104]
12-17 18:26:09.000 14613-14613/com.example.TestPlugin:PluginP02 W/asset: Looking for non-asset 'res/drawable-xhdpi/main_bottom_4_dw.png' in '/data/data/com.example.TestPlugin/Plugin/com.besttone.tavem/apk/base-1.apk'
12-17 18:26:09.020 14613-14613/com.example.TestPlugin:PluginP02 W/Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
12-17 18:26:09.213 14613-14613/com.example.TestPlugin:PluginP02 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4166ad70)
12-17 18:26:09.237 14613-14613/com.example.TestPlugin:PluginP02 W/System.err: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.push.receiver.PushNetReceiver@422b8698
12-17 18:26:09.237 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:769)
12-17 18:26:09.237 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
12-17 18:26:09.237 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-17 18:26:09.237 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5345)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:855)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
12-17 18:26:09.238 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err: Caused by: java.lang.SecurityException: Package com.besttone.tavem does not belong to 10204
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Parcel.readException(Parcel.java:1472)
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.content.ContentProviderProxy.call(ContentProviderNative.java:636)
12-17 18:26:09.239 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:903)
12-17 18:26:09.240 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.provider.Settings$System.putStringForUser(Settings.java:1175)
12-17 18:26:09.240 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.provider.Settings$System.putIntForUser(Settings.java:1288)
12-17 18:26:09.240 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.provider.Settings$System.putInt(Settings.java:1282)
12-17 18:26:09.241 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at com.gdc.third.pay.ds.GdcPushSetting.updateBootComplete(Unknown Source)
12-17 18:26:09.241 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at com.gdc.third.pay.util.Util.a(Unknown Source)
12-17 18:26:09.241 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at org.push.receiver.PushNetReceiver.onReceive(Unknown Source)
12-17 18:26:09.241 14613-14613/com.example.TestPlugin:PluginP02 W/System.err:     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:759)
12-17 18:26:09.241 14613-14613/com.example.TestPlugin:PluginP02 W/System.err: 	... 9 more

**Comment by cmzy** [comment]
fixed on https://github.com/Qihoo360/DroidPlugin/commit/1de0855ef64a3857d475e4e9708eebad92e43b75
