### ISSUE TITLE
插件间公用库问题？

### ISSUE THREAD

**Issue by leon49** [Qihoo360/DroidPlugin#11]
1.demo中 TestPlugin 是把DroidPlugin库给compile编译进去了
compile project(':Libraries:DroidPlugin')
为何不用 provided?

2.不同插件之间能否共用 带有资源的库？
provided 只能对.jar包进行引用
而有共用资源的共有库怎么共享呢（drawable下的资源 values下的配置）？

**Comment by cmzy** [comment]
1、请参阅gradle文档。
2、不行。

leon49 <notifications@github.com>于2015年9月7日 周一20:33写道：
