### ISSUE TITLE
有人运行过QQ吗? 用DroidPlugin

### ISSUE THREAD

**Issue by tianqiujie** [Qihoo360/DroidPlugin#110]
有人运行过QQ吗? 用DroidPlugin  我试过 不行  把所有的权限都添加了的 然后点登陆按钮 直接退出

**Comment by cmzy** [comment]
重复：https://github.com/Qihoo360/DroidPlugin/issues/105

**Comment by slimboy2008** [comment]
可以运行QQ，能进登录页面，但是无法连接网络

**Comment by the-sparrow** [comment]
@tianqiujie @cmzy @slimboy2008 有最终解决方案吗

**Comment by zhengbobo** [comment]
@slimboy2008 问题解决了吗
