### ISSUE TITLE
插件引so包出现问题

### ISSUE THREAD

**Issue by yanglinglong1** [Qihoo360/DroidPlugin#111]
插件引 so 包，在 64位机器上出现如下错误。

12-28 17:16:16.051 26681-26681/? E/art: dlopen("/data/data/com.example.TestPlugin/Plugin/com.jingoal.mobile.android.jingoal/lib/libstlport_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.example.TestPlugin/Plugin/com.jingoal.mobile.android.jingoal/lib/libstlport_shared.so" is 32-bit instead of 64-bit

**Comment by cmzy** [comment]
请参照：https://github.com/Qihoo360/DroidPlugin/commit/534a970440ff149f369f5a11611b191523a0ebe7

**Comment by francis-git** [comment]
现在可以32位的os库在64位手机上跑起来了吗？请教
