### ISSUE TITLE
启动插件Activity时，宿主设置的intent无法传递到插件？

### ISSUE THREAD

**Issue by yongganShaonian** [Qihoo360/DroidPlugin#113]
启动插件Activity，在intent中设置了一个flags（Intent.FLAG_ACTIVITY_NO_USER_ACTION），但是打开插件后并没有起到作用。

**Comment by DavidYes** [comment]
我也碰到一样的问题：
startactivity的时候，addFlag无效，比如 intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

intent.addFlags(Intent.FLAG_ACTIVITY_NO_USER_ACTION);

之前非动态加载的版本都可以正常使用，但是引入droidplugin后这些flag就失效，
对应intent传值，比如 public Intent putExtra(String name, Serializable value) 
无法正常传递 序列化的对象到相应的activity;

**Comment by cmzy** [comment]
fixed on https://github.com/Qihoo360/DroidPlugin/commit/b5f5b51c32cf98573efcf4a5125c82315fc9311a
