### ISSUE TITLE
这是目前国内最优秀的动态加载的框架，恳请大牛 Andy Zhang 开一个QQ群 方便交流？

### ISSUE THREAD

**Issue by DavidYes** [Qihoo360/DroidPlugin#114]
我现在发现比较棘手的几件事情：
1，在 锤子 手机上hook webview的时候，必然闪退；
2，startactivity的时候，addFlag无效，比如 intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
intent.addFlags(Intent.FLAG_ACTIVITY_NO_USER_ACTION);
之前非动态加载的版本都可以正常使用，但是引入droidplugin后这些flag就失效，
3，对应intent传值，比如 public Intent putExtra(String name, Serializable value) 
无法正常传递 序列化的对象到相应的activity;

**Comment by KevinLee007** [comment]
我与楼主遇到了相同的问题1

**Comment by cmzy** [comment]
fixed：QQ群：318901026
具体问题请另外开一个issue
