### ISSUE TITLE
不能运行经过360加固的apk包

### ISSUE THREAD

**Issue by tbfly** [Qihoo360/DroidPlugin#116]
D/dalvikvm(27473): Trying to load lib /data/data/com.example.TestPlugin/Plugin/com.vipshare/data/com.vipshare/files/libjiagu.so 0x41bc7d80
D/dalvikvm(27473): Added shared lib /data/data/com.example.TestPlugin/Plugin/com.vipshare/data/com.vipshare/files/libjiagu.so 0x41bc7d80
I/dalvikvm(27495): Turning on JNI app bug workarounds for target SDK version 8...
W/System.err(27473): java.lang.ClassNotFoundException: Didn't find class "com.qihoo360.crypt.entryRunApplication" on path: DexPathList[[zip file "/data/data/com.example.TestPlugin/Plugin/com.vipshare/apk/base-1.apk"],nativeLibraryDirectories=[/data/data/com.example.TestPlugin/Plugin/com.vipshare/lib, /vendor/lib, /system/lib]]
W/System.err(27473): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
W/System.err(27473): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err(27473): 	at com.morgoo.droidplugin.core.PluginClassLoader.loadClass(PluginClassLoader.java:71)
W/System.err(27473): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err(27473): 	at com.qihoo.util.StubApplication.getNewAppInstance(StubApplication.java:43)
W/System.err(27473): 	at com.qihoo.util.StubApplication.attachBaseContext(StubApplication.java:135)
W/System.err(27473): 	at android.app.Application.attach(Application.java:181)
W/System.err(27473): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
W/System.err(27473): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
W/System.err(27473): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
W/System.err(27473): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(27473): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err(27473): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:214)
W/System.err(27473): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
W/System.err(27473): 	at com.morgoo.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:272)
W/System.err(27473): 	at com.morgoo.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:228)
W/System.err(27473): 	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:380)
W/System.err(27473): 	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:251)
W/System.err(27473): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(27473): 	at android.os.Looper.loop(Looper.java:137)
W/System.err(27473): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
W/System.err(27473): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(27473): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err(27473): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
W/System.err(27473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
W/System.err(27473): 	at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(27473): JNI WARNING: JNI method called with exception pending
W/dalvikvm(27473):              in Lcom/qihoo/util/StubApplication;.interface8:(Landroid/app/Application;Landroid/content/Context;)Z (GetFieldID)
W/dalvikvm(27473): Pending exception is:
I/dalvikvm(27473): java.lang.NullPointerException:
I/dalvikvm(27473): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5031)
I/dalvikvm(27473): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4671)
I/dalvikvm(27473): 	at com.qihoo.util.StubApplication.interface8(Native Method)
I/dalvikvm(27473): 	at com.qihoo.util.StubApplication.attachBaseContext(StubApplication.java:147)
I/dalvikvm(27473): 	at android.app.Application.attach(Application.java:181)
I/dalvikvm(27473): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
I/dalvikvm(27473): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
I/dalvikvm(27473): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
I/dalvikvm(27473): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(27473): 	at java.lang.reflect.Method.invoke(Method.java:525)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:214)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:272)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:228)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:380)
I/dalvikvm(27473): 	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:251)
I/dalvikvm(27473): 	at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm(27473): 	at android.os.Looper.loop(Looper.java:137)
I/dalvikvm(27473): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
I/dalvikvm(27473): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(27473): 	at java.lang.reflect.Method.invoke(Method.java:525)
I/dalvikvm(27473): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
I/dalvikvm(27473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
I/dalvikvm(27473): 	at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(27473): "main" prio=5 tid=1 NATIVE
I/dalvikvm(27473):   | group="main" sCount=0 dsCount=0 obj=0x41823638 self=0x417b4228
I/dalvikvm(27473):   | sysTid=27473 nice=0 sched=0/0 cgrp=apps handle=1074135292
I/dalvikvm(27473):   | state=R schedstat=( 529593413 77103328 639 ) utm=37 stm=15 core=1
I/dalvikvm(27473):   #00  pc 000012fe  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
I/dalvikvm(27473):   #01  pc 00061582  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+33)
I/dalvikvm(27473):   #02  pc 00055614  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
I/dalvikvm(27473):   #03  pc 00055682  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm(27473):   #04  pc 00039b34  /system/lib/libdvm.so
I/dalvikvm(27473):   #05  pc 0003fba4  /system/lib/libdvm.so
I/dalvikvm(27473):   at com.qihoo.util.StubApplication.interface8(Native Method)
I/dalvikvm(27473):   at com.qihoo.util.StubApplication.attachBaseContext(StubApplication.java:147)
I/dalvikvm(27473):   at android.app.Application.attach(Application.java:181)
I/dalvikvm(27473):   at android.app.Instrumentation.newApplication(Instrumentation.java:991)
I/dalvikvm(27473):   at android.app.Instrumentation.newApplication(Instrumentation.java:975)
I/dalvikvm(27473):   at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
I/dalvikvm(27473):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(27473):   at java.lang.reflect.Method.invoke(Method.java:525)
I/dalvikvm(27473):   at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:214)
I/dalvikvm(27473):   at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
I/dalvikvm(27473):   at com.morgoo.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:272)
I/dalvikvm(27473):   at com.morgoo.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:228)
I/dalvikvm(27473):   at com.morgoo.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:380)
I/dalvikvm(27473):   at com.morgoo.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:251)
I/dalvikvm(27473):   at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm(27473):   at android.os.Looper.loop(Looper.java:137)
I/dalvikvm(27473):   at android.app.ActivityThread.main(ActivityThread.java:5289)
I/dalvikvm(27473):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(27473):   at java.lang.reflect.Method.invoke(Method.java:525)
I/dalvikvm(27473):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
I/dalvikvm(27473):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
I/dalvikvm(27473):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(27473): 
E/dalvikvm(27473): VM aborting
F/libc    (27473): Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 27473 (com.vipshare)

比如上面这种app。
提示 com.qihoo360.crypt.entryRunApplication 找不到。

**Comment by cmzy** [comment]
重复了https://github.com/Qihoo360/DroidPlugin/issues/127

**Comment by cmzy** [comment]
确实无法运行加固后的包。先close
