### ISSUE TITLE
除了LAUNCH_MULTIPLE，其他启动方式的acitivity是否只能有一个

### ISSUE THREAD

**Issue by ly85206559** [Qihoo360/DroidPlugin#119]
预定义的一些activity看代码只有LAUNCH_MULTIPLE会重用，其他的是能有一个
if (stubInfo.launchMode == ActivityInfo.LAUNCH_MULTIPLE) {
                                    mRunningProcessList.setTargetProcessName(stubInfo, targetInfo);
                                    return stubInfo;
                                } else if (!mRunningProcessList.isStubInfoUsed(stubInfo, targetInfo, stubProcessName1)) {
                                    mRunningProcessList.setTargetProcessName(stubInfo, targetInfo);
                                    return stubInfo;
                                }

**Comment by cmzy** [comment]
不是。可以有多个，我做了适配的。
