### ISSUE TITLE
installPackage 返回 -1 ？？？

### ISSUE THREAD

**Issue by xueshiju** [Qihoo360/DroidPlugin#12]
String filepath = "/data/data/com.goldflower.main/files/abc.apk";
		int installpackage;
		try {
			installpackage = PluginManager.getInstance().installPackage( filepath, 0);
			Debug.print("installpackage="+installpackage);
		} catch (RemoteException e) {
			e.printStackTrace();
		}

**Comment by Grasswolf** [comment]
我也遇到这个问题了，有神马解决方法么

**Comment by cmzy** [comment]
是因为manifest没有被合并到主工程的manifest中，编译时开启menifest合并选项就可以了。
