### ISSUE TITLE
关于IMountServiceHookHandle类

### ISSUE THREAD

**Issue by GodLikeJed** [Qihoo360/DroidPlugin#124]
在4.2下demo没有问题，但是在4.4.2下的联想pad上出现了问题，在打开已安装插件时弹出。大神的回复是，需要修改IMountServiceHookHandle这个类。因为他没对你读取obb目录的时候，没做重定向。这个是Caused by: java.lang.SecurityException: Invalid mkdirs path: /storage/sdcard1/Android/obb/com.DSIdeal.BanLiHuZhao/
判断的时候只是有android data
日志如下：
01-25 09:56:01.602: E/PackageParser(4274): LenovoSafe enable
01-25 09:56:01.602: E/IntentFilter(4274): countrycode= CN
01-25 09:56:09.748: E/MtkAgps(4918): [MtkAgpsManagerService][agps] ERR: ERR: getService() sService is still null.. 
01-25 09:56:09.765: E/MtkAgps(4918): [MtkAgpsManagerService][agps] ERR: ERR: getService() sService is still null.. 
01-25 09:56:09.806: E/AndroidRuntime(4918): FATAL EXCEPTION: main
01-25 09:56:09.806: E/AndroidRuntime(4918): Process: com.example.TestPlugin:PluginP02, PID: 4918
01-25 09:56:09.806: E/AndroidRuntime(4918): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.DSIdeal.BanLiHuZhao/com.unity3d.player.UnityPlayerNativeActivity}: java.lang.SecurityException: Invalid mkdirs path: /storage/sdcard1/Android/obb/com.DSIdeal.BanLiHuZhao/
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.os.Handler.dispatchMessage(Handler.java:110)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.os.Looper.loop(Looper.java:193)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at dalvik.system.NativeStart.main(Native Method)
01-25 09:56:09.806: E/AndroidRuntime(4918): Caused by: java.lang.SecurityException: Invalid mkdirs path: /storage/sdcard1/Android/obb/com.DSIdeal.BanLiHuZhao/
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.os.Parcel.readException(Parcel.java:1465)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.os.Parcel.readException(Parcel.java:1419)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.os.storage.IMountService$Stub$Proxy.mkdirs(IMountService.java:750)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:51)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.morgoo.droidplugin.hook.binder.BinderHook.invoke(BinderHook.java:57)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.morgoo.droidplugin.hook.binder.IMountServiceBinder.invoke(IMountServiceBinder.java:1)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at $Proxy4.mkdirs(Native Method)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ContextImpl.ensureDirsExistOrFilter(ContextImpl.java:2265)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ContextImpl.getObbDirs(ContextImpl.java:979)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ContextImpl.getObbDir(ContextImpl.java:968)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.content.ContextWrapper.getObbDir(ContextWrapper.java:220)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.NativeActivity.onCreate(NativeActivity.java:177)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.unity3d.player.UnityPlayerNativeActivity.onCreate(Unknown Source)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.Activity.performCreate(Activity.java:5264)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:95)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
01-25 09:56:09.806: E/AndroidRuntime(4918): 	... 11 more

**Comment by cmzy** [comment]
fixed on https://github.com/Qihoo360/DroidPlugin/commit/083835c353d82992f9d231416f03f5edfeedeb5e
