### ISSUE TITLE
联想平板（A10-70F）android5.0下问题

### ISSUE THREAD

**Issue by GodLikeJed** [Qihoo360/DroidPlugin#125]
日志如下：
01-26 08:48:18.058: E/MPlugin(27984): Unsupported class: com.mediatek.common.audioprofile.IAudioProfileExtension$IDefaultProfileStatesGetter
01-26 08:48:18.080: E/MPlugin(27984): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
01-26 08:48:18.104: E/MPlugin(27984): Unsupported class: com.mediatek.common.audioprofile.IAudioProfileExtension$IDefaultProfileStatesGetter
01-26 08:48:18.108: E/MPlugin(27984): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
01-26 08:48:18.133: E/AndroidRuntime(27984): FATAL EXCEPTION: main
01-26 08:48:18.133: E/AndroidRuntime(27984): Process: com.example.TestPlugin:PluginP04, PID: 27984
01-26 08:48:18.133: E/AndroidRuntime(27984): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.DSIdeal.QingDaoXiangMu/com.unity3d.player.UnityPlayerNativeActivity}: java.lang.IllegalArgumentException: Unable to find native library: main
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread.access$800(ActivityThread.java:167)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.os.Handler.dispatchMessage(Handler.java:111)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.os.Looper.loop(Looper.java:194)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread.main(ActivityThread.java:5534)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at java.lang.reflect.Method.invoke(Native Method)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
01-26 08:48:18.133: E/AndroidRuntime(27984): Caused by: java.lang.IllegalArgumentException: Unable to find native library: main
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.NativeActivity.onCreate(NativeActivity.java:170)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at com.unity3d.player.UnityPlayerNativeActivity.onCreate(Unknown Source)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.Activity.performCreate(Activity.java:5971)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:95)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
01-26 08:48:18.133: E/AndroidRuntime(27984): 	... 10 more

**Comment by cmzy** [comment]
com.DSIdeal.QingDaoXiangMu这是个什么APK？看日志是找不到SO，能否把apk发上来看看。

**Comment by GodLikeJed** [comment]
@cmzy 不是APK的问题，试过很多在应用商店下载的apk都安装不了

**Comment by cmzy** [comment]
啊？那到底是不是apk自己的问题？

**Comment by GodLikeJed** [comment]
@cmzy 绝对不是apk的问题 因为除了这个apk之外 其他的apk都装不了。并且在安卓4.2系统完美安装。这个板子cpu是64位的，不知道跟这个有没有兼容性问题。。

**Comment by cmzy** [comment]
那估计是64位的问题。

**Comment by cmzy** [comment]
64位so的问题，请参照：https://github.com/Qihoo360/DroidPlugin/commit/534a970440ff149f369f5a11611b191523a0ebe7
