### ISSUE TITLE
安装不了呢，我的工程里也没有provider啊

### ISSUE THREAD

**Issue by sfsheng0322** [Qihoo360/DroidPlugin#129]
这是安装不了的log：
Package couldn't be installed in /data/app/com.sun.study-1
 com.android.server.pm.PackageManagerException: Can't install because provider name com.morgoo.droidplugin_stub_P00 (in package com.sun.study) is already used by com.ttcode.appdirect
at com.android.server.pm.PackageManagerService.scanPackageDirtyLI (PackageManagerService.java:5707)

**Comment by tiann** [comment]
不看文档啊亲，文档  使用方法->集成     第四步。

**Comment by sfsheng0322** [comment]
哈，是DroidPlugin\AndroidManifest.xml中所有的provider啊，怪我喽，谢谢你哈。
