### ISSUE TITLE
IMountServiceHookHandle$mkdirs中的beforeInvoke()逻辑似乎有问题?

### ISSUE THREAD

**Issue by stevenbadlogic** [Qihoo360/DroidPlugin#130]
嗨，拜读了您的代码，涨了不少姿势，十分感谢！

我有个疑惑，IMountServiceHookHandle$mkdirs中的beforeInvoke()中，您的想法应该是判断路径如果是插件的路径，就重定向为框架中的插件路径吧，isAndroiDataHostPath这个内部变量判断时，如果路径是"Android/obb/com.test.xxx"岂非也会为 true, 那根本走不进去"Android/obb"的替换逻辑块中额。

期待你的回复，再次感谢～

**Comment by cmzy** [comment]
确是有bug。我修改下。
