### ISSUE TITLE
红米手机使用TestPlugin，打开插件apk时候，不能正常打开

### ISSUE THREAD

**Issue by aidaima** [Qihoo360/DroidPlugin#133]
再红米手机上，使用TestPlugin工程，打开已安装的插件时，不能正常打开，以下情况会交替出现：
第一次点击打开，可以正常打开插件apk
手动退出插件
第二次点击打开，出现“努力加载中...”界面，一直显示，不能正常显示插件界面
手动返回
第三次点击打开，可以正常打开插件apk
手动退出插件
第四次点击打开，出现“努力加载中...”界面，一直显示，不能正常显示插件界面

**Comment by GamePlug** [comment]
小米3也有这个问题，2016年2月26日上午下载最新的代码运行的。

**Comment by soaringEveryday** [comment]
小米4手机也是这样，求解

**Comment by cmzy** [comment]
请查看这一节：


将插件中Libraries\DroidPlugin\AndroidManifest.xml中所有的provider对应的authorities修改成自己的，默认为com.morgoo.droidplugin_stub_P00，如下：

<provider
    android:name="com.morgoo.droidplugin.stub.ContentProviderStub$StubP00"
    android:authorities="com.morgoo.droidplugin_stub_P00"
    android:exported="false"
    android:label="@string/stub_name_povider" />
可以修改为自己的包名，如: com.example.droidplugin_stub_P00 防止跟其它本插件使用者冲突：

<provider
    android:name="com.morgoo.droidplugin.stub.ContentProviderStub$StubP00"
    android:authorities="com.example.droidplugin_stub_P00"
    android:exported="false"
    android:label="@string/stub_name_povider" />
并且修改PluginManager.STUB_AUTHORITY_NAME 为你的值:

PluginManager.STUB_AUTHORITY_NAME="com.example.droidplugin_stub"
