### ISSUE TITLE
【question】插件以自定义的action发送的广播，宿主程序无法接收吗？

### ISSUE THREAD

**Issue by Mortimer2013** [Qihoo360/DroidPlugin#134]
我在插件中发送自定义action的广播，在宿主中无法接收。自己另外建的一个apk可以接收到插件发送的广播（插件已安装），请问这个是限制吗？文档中写的不是很清楚。谢谢。

**Comment by cmzy** [comment]
可以啊。。我试试。。理论上是可以得，没有限制。
