### ISSUE TITLE
在华为p8青春版上无法正常安装插件

### ISSUE THREAD

**Issue by oceanheart** [Qihoo360/DroidPlugin#136]
硬件信息：
华为P8 ALE-TL00 
Android 5.0.2 
EMUI 3.1

问题描述：
宿主能正常安装，但安装插件时出现问题。现像是无法正常安装，下次启动时log报各种类找不到，so找不到等。由于 手机无法ROOT无法确认相应的文件是否在存储卡不存在。

辅助描述：
360手机助手无法在此手机上安装，系统提示安装失败。

**Comment by cmzy** [comment]
1、编译的时候保证合并manifest的选项打开。
2、请用adb 命令安装助手，然后把错误码发给我一下。

**Comment by oceanheart** [comment]
问题已经定位
跟踪代码发现因缺少两个huawei的私有权限，在库中增加上下面两个权限之后问题就解决了。
    <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS"/>
