### ISSUE TITLE
DroidPlugin integrate error

### ISSUE THREAD

**Issue by locht710** [Qihoo360/DroidPlugin#139]
I'm using DroidPlugin in my app. I did the tutorial from readme to integrate but I have a problem.

I changed manifest, add custom code to MyApplication class, but cannot change PluginManager.STUB_AUTHORITY_NAME because it's final. 
After I installpackage with method: int PluginManager.getInstance().installPackage(String filepath, int flags); 
It's always return -1!
I run my apk on MainActivity as follow:
            PackageManager pm = this.getPackageManager();
            Intent intent = pm.getLaunchIntentForPackage("mypackagename");
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);
I catch an exception null reference object!!!
How can I fix this? I'm missing something??Who can provide me a more detail instruction about DroidPlugin?
Thanks a lot.

**Comment by cmzy** [comment]
Please :
1. just change it on the source code .....
2. set manifestmerger enabled option to true
