### ISSUE TITLE
提示安装失败，文件请求的权限太多

### ISSUE THREAD

**Issue by llew2011** [Qihoo360/DroidPlugin#141]
测试 央视影音.apk 时提示“提示安装失败，文件请求的权限太多”，通过跟踪代码发现是配置文件中缺少"android.permission.INTERACT_ACROSS_USERS_FULL"权限

**Comment by cmzy** [comment]
加上这个权限就成了。

**Comment by mcdonaldLiu** [comment]
似乎加上了还是无效  提示请求权限太多

**Comment by cmzy** [comment]
没加完全

**Comment by mcdonaldLiu** [comment]
什么意思   <uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL"/> 我加了这个啊

**Comment by mcdonaldLiu** [comment]
<uses-permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL"/>

**Comment by mcdonaldLiu** [comment]
还需要加什么别的权限  难道？
