### ISSUE TITLE
IWindowManagerBinderHook 之fixWindowManagerHook

### ISSUE THREAD

**Issue by ForrestVV** [Qihoo360/DroidPlugin#144]
下面的逻辑判断：          
  if (obj != proxiedObj) {
                return;
            }
应该修改为：
  if (obj == proxiedObj) {
                return;
            }
吧？

**Comment by cmzy** [comment]
fixed on https://github.com/Qihoo360/DroidPlugin/commit/a740ea545162aeb3dc75c8ea3bf0409af6d1cd8f
