### ISSUE TITLE
failjava.lang.NoSuchMethodException: generatePackageInfo  [class android.content.pm.PackageParser$Package, class [I, int, long,...

### ISSUE THREAD

**Issue by cayden** [Qihoo360/DroidPlugin#146]
启动后出现如下日志：通过查看PackageParse的源码 发现参数没有出错呢，但是还是报了下面错误日志
机型：一加 华为
android 版本 5.1.1    4.2.2
` I/PackageParserApi21: get generatePackageInfo 2 failjava.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, class java.util.HashSet, class android.content.pm.PackageUserState, int]
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at java.lang.Class.getMethod(Class.java:664)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at java.lang.Class.getMethod(Class.java:643)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:199)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.pm.parser.PackageParserApi22.generatePackageInfo(PackageParserApi22.java:57)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:364)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.pm.IPluginManagerImpl.getInstalledPackages(IPluginManagerImpl.java:555)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.morgoo.droidplugin.pm.PluginManager.getInstalledPackages(PluginManager.java:465)
03-16 14:19:51.232 10449-10480/com.example.TestPlugin I/PackageParserApi21:     at com.example.TestPlugin.InstalledFragment$2.run(InstalledFragment.java:90)
03-16 14:19:51.233 10449-10449/com.example.TestPlugin W/asset: Asset path /system/framework/oneplus-framework-res.apk is neither a directory nor file (type=1).`

**Comment by cayden** [comment]
已经没有问题了，这里是使用了三种方式来进行反射处理 ，所以会出现这种日志。

**Comment by SnowDragon2015** [comment]
请问楼主怎么解决的，我的也是出现java.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, class java.util.HashSet, class android.content.pm.PackageUserState, int]  这个问题
