### ISSUE TITLE
直接导入解压缩后的项目文件project,运行的时候报如下错误，能帮忙分析下吗

### ISSUE THREAD

**Issue by github2013j** [Qihoo360/DroidPlugin#153]
![qq 20160324171558](https://cloud.githubusercontent.com/assets/6291941/14012985/825a3224-f1e4-11e5-8aa7-82d3c98752ce.png)

gradle version 2.2
android plugin version 1.3.0
编译sdk  version API  22

**Comment by SheepYoung** [comment]
现在master 的代码是有这个的 文件: layoutlib.jar

**Comment by github2013j** [comment]
你好，下载的文件中没有你说的layoutib.jar，另外，即使有这个jar，你的意思是导入这个jar包就不报错？

**Comment by SheepYoung** [comment]
详细路径： DroidPlugin/project/Libraries/DroidPlugin/lib/layoutlib.jar  你自己看看是不是下载错代码了。

**Comment by github2013j** [comment]
非常感谢你的答疑，我是用的其他github上转载的droidplugin源码。现在我从该官网下载了对应的项目文件，没有上面的问题，但是编译的过程中，提示如下错误
![72g5i1 pzi5ayn8 z6v wmo](https://cloud.githubusercontent.com/assets/6291941/14036300/9d117ba2-f272-11e5-9e20-e76c809d8b27.png)
这个了解吗？

**Comment by cmzy** [comment]
这是最新的测试代码中加了ndk的测试，你需要设置你的ndk路径，或者在gradle编译脚本中禁用掉ndk编译选项。
