### ISSUE TITLE
IPluginManager:can't find import class

### ISSUE THREAD

**Issue by a6511631** [Qihoo360/DroidPlugin#2]
Droid Plugin的library中，IPluginManager中关于以下的引用会提示can't find import class，如下图。
![image](https://cloud.githubusercontent.com/assets/10797268/9560315/c629b8a6-4e3f-11e5-93f0-659c8e5b02da.png)
网上的资料提出要去修改framework层的frameworks/base/Android.mk。除此之外，您能否给一点帮助呢

**Comment by cnzx219** [comment]
你可以尝试提高一下compileSdk的api等级到21或者22，过去没有开放的api，现在很多已经开放了。这个也不影响minSdk
已经开放的api，定义被修改的可能性非常小了。

**Comment by SSOOnline** [comment]
DroidPlugin\project\Libraries\DroidPlugin\src\com\morgoo\droidplugin\hook\proxy\IActivityManagerHook.java:91: 错误: 找不到符号

**Comment by cnzx219** [comment]
楼上这位，把你的log打全一点好吗

**Comment by codehz** [comment]
@a6511631 的问题一般是SDK版本问题，我用Android 6.0的SDK23就没这个问题。。。

**Comment by 116205035** [comment]
@a6511631  SDK 22 及以上都可以

**Comment by cmzy** [comment]
close, sdk must be 22 or later

**Comment by agoodcoolman** [comment]
我用android Studio 1.5 已经将targetSDK 调整到了23，但是还是没找到。
