### ISSUE TITLE
奇数次数打不开

### ISSUE THREAD

**Issue by GreenVegetables** [Qihoo360/DroidPlugin#20]
奇数次数卡在加载中界面，用的是最新代码，authorities修改前与修改后都一样

**Comment by cmzy** [comment]
已经解决了，请更新，并重新集成，文档我少写了个地方。
and change PluginManager.STUB_AUTHORITY_NAME to your value:

  PluginManager.STUB_AUTHORITY_NAME="com.example.droidplugin_stub"

**Comment by mcdonaldLiu** [comment]
我也遇到了  隔一次才能打开？
