### ISSUE TITLE
修改provider的authorities后第一次无法打开

### ISSUE THREAD

**Issue by Helen-Guo** [Qihoo360/DroidPlugin#21]
不修改authorities的话是正常的，修改之后第一次进就停在加载界面不动了，退出再进的话又正常可以进去了，但是清理内存进程后，又跟上面一样了，需要两次才能进入，这个是怎么回事呢

**Comment by outerman** [comment]
相同的问题，花了我一天时间跟踪，解决办法：
修改PluginProcessManager类的120行，有这样的一个判断info.authority.indexOf("com.morgoo.droidplugin_stub") < 0)，字符串替换为自己修改的authorities的名称

**Comment by Helen-Guo** [comment]
我也找到解决办法了，如果主项目本身没有provider的话，可以把DroidPlugin中的provider全部去掉就正常了，如果需要provider的话，可以在原有authorities名字前面添加任意字符串，不删除原来的authorities里面的com.morgoo.droidplugin_stub字符串就可以了，这样就不用修改内部代码了！
