### ISSUE TITLE
关于修改authorities后，奇数次打不开的问题，及解决方法

### ISSUE THREAD

**Issue by outerman** [Qihoo360/DroidPlugin#22]
关于修改authorities后，奇数次打不开的问题，花了我一天时间跟踪，解决办法：

修改PluginProcessManager类的120行，有这样的一个判断info.authority.indexOf("com.morgoo.droidplugin_stub") < 0)，字符串替换为自己修改的authorities名称的统一前缀。自测修改后正常！

猜测原因，在判断在判断是否是插件进程时候，根据authorities的前缀做判断，然而在代码中只判断了默认的authorities，如果自己修改了authorities，这个判断就失效了。导致初始化过程耗时较长，在初始化完成前，PluginCallback就收到了LAUNCH_ACTIVITY消息，此时PluginCallback.mEnable 的值为false，没有执行PluginCallback.handleLaunchActivity()方法，界面就没有加载出来。

不知道分析的是否正确，还请开发团队关注

**Comment by LLbgithub** [comment]
我貌似也遇到了，我试试看看，谢谢
