### ISSUE TITLE
插件apk的本地H5页面使用了assert目录下的css,用DroidPlugin打开后不会被识别

### ISSUE THREAD

**Issue by dustookk** [Qihoo360/DroidPlugin#23]
插件apk的assert目录下有一个index.html, 其中对 ***css的引用*** 是这么写的:

        <link href="file:///android_asset/css.css" type="text/css" rel="stylesheet" />

意思是引用了assert目录下的一个css样式表. 

用DroidPlugin打开后样式错乱, ***css没有被识别*** .

**Comment by dustookk** [comment]
[测试apk](http://app.sina.com.cn/appdetail.php?appID=1196010)

**Comment by wywlds** [comment]
因为不能使用file:///android_asset/打开，我的方案是在代码里面把asset里面的字符串取出来，然后使用webView.loadDataWithBaseUrl接口来加载。
或许作者有更好的办法。

**Comment by cmzy** [comment]
测试了一下，不用插件机制，让俩app运行在同一个进程，第二个app中如果有webview，且在html中通过```file:///android_asset/```来指定资源的时候，也会出现找不到资源的问题。具体原因如下：


在如下frameworks\webview\chromium\java\com\android\webview\chromium\WebViewChromiumFactoryProvider.java

[WebViewChromiumFactoryProvider.java](https://android.googlesource.com/platform/frameworks/webview/+/kitkat-cts-dev/chromium/java/com/android/webview/chromium/WebViewChromiumFactoryProvider.java)

···Java
   
private void startChromiumLocked() {
        assert Thread.holdsLock(mLock) && ThreadUtils.runningOnUiThread();

        // The post-condition of this method is everything is ready, so notify now to cover all
        // return paths. (Other threads will not wake-up until we release |mLock|, whatever).
        mLock.notifyAll();

        if (mStarted) {
            return;
        }

        if (Build.IS_DEBUGGABLE) {
            CommandLine.initFromFile(COMMAND_LINE_FILE);
        } else {
            CommandLine.init(null);
        }

        CommandLine cl = CommandLine.getInstance();
        // TODO: currently in a relase build the DCHECKs only log. We either need to insall
        // a report handler with SetLogReportHandler to make them assert, or else compile
        // them out of the build altogether (b/8284203). Either way, so long they're
        // compiled in, we may as unconditionally enable them here.
        cl.appendSwitch("enable-dcheck");

        // TODO: Remove when GL is supported by default in the upstream code.
        if (!cl.hasSwitch("disable-webview-gl-mode")) {
            cl.appendSwitch("testing-webview-gl-mode");
        }

        Context context = ActivityThread.currentApplication();
        if (context.getApplicationInfo().targetSdkVersion < Build.VERSION_CODES.KITKAT) {
            cl.appendSwitch("enable-webview-classic-workarounds");
        }

        // We don't need to extract any paks because for WebView, they are
        // in the system image.
        ResourceExtractor.setMandatoryPaksToExtract("");

        try {
            LibraryLoader.ensureInitialized();
        } catch(ProcessInitException e) {
            throw new RuntimeException("Error initializing WebView library", e);
        }

        PathService.override(PathService.DIR_MODULE, "/system/lib/");
        // TODO: DIR_RESOURCE_PAKS_ANDROID needs to live somewhere sensible,
        // inlined here for simplicity setting up the HTMLViewer demo. Unfortunately
        // it can't go into base.PathService, as the native constant it refers to
        // lives in the ui/ layer. See ui/base/ui_base_paths.h
        final int DIR_RESOURCE_PAKS_ANDROID = 3003;
        PathService.override(DIR_RESOURCE_PAKS_ANDROID,
                "/system/framework/webview/paks");

        AwBrowserProcess.start(ActivityThread.currentApplication());
        initPlatSupportLibrary();

        if (Build.IS_DEBUGGABLE) {
            setWebContentsDebuggingEnabled(true);
        }
        mStarted = true;

        for (WeakReference<WebViewChromium> wvc : mWebViewsToStart) {
            WebViewChromium w = wvc.get();
            if (w != null) {
                w.startYourEngine();
            }
        }
        mWebViewsToStart.clear();
        mWebViewsToStart = null;
}
···

类中加载WebView，启动Chromium引擎的时候，使用的不是WebView对象的```Context```，而是```ActivityThread.currentApplication()```：

```java
AwBrowserProcess.start(ActivityThread.currentApplication());
```
从而导致在Native代码中的```Context```对象为当前进程中主app的```Context```，在加载资源时则去主```Context```中找寻资源，自然就加载不到了，加载过程在```org.chromium.android_webview.AndroidProtocolHandler.open()```方法：

[AndroidProtocolHandler.java](https://chromium.googlesource.com/chromium/src.git/+/d0ef9df6be5983f6df7e4e050bbad4eb5030e7a2/android_webview/java/src/org/chromium/android_webview/AndroidProtocolHandler.java)

```Java
    @CalledByNativeUnchecked
    public static InputStream open(Context context, String url) {
        Uri uri = verifyUrl(url);
        if (uri == null) {
            return null;
        }
        String path = uri.getPath();
        if (uri.getScheme().equals(FILE_SCHEME)) {
            if (path.startsWith(nativeGetAndroidAssetPath())) {
                return openAsset(context, uri);
            } else if (path.startsWith(nativeGetAndroidResourcePath())) {
                return openResource(context, uri);
            }
        } else if (uri.getScheme().equals(CONTENT_SCHEME)) {
            return openContent(context, uri);
        }
        return null;
    }
```

以上在Android6.0上复现。目前只是研究结果，还需要进一步研究。

**Comment by cmzy** [comment]
fixed on commit https://github.com/Qihoo360/DroidPlugin/commit/971b672e70a55f8b1a3ff986ad6259cab60b7539

**Comment by cmzy** [comment]
经过验证，这个问题的机型适配列表。
1、API 10-15 不存在
2、APi 16-18 不存在
3、API 19-21 存在
4、API 22-23 or later 存在

**Comment by jamin918** [comment]
这个问题并没有解决，怎么关闭了呢？

**Comment by dustookk** [comment]
貌似作者已经修复了吧.

当时我临时解决办法是把file:///android_asset/wh.css  换成 file:///sdcard/xh.css

**Comment by jamin918** [comment]
@dustookk  没有解决，依然提示：Unable to open asset URL: file:///android_asset/www/fullscreen/index.html，在WebViewFactoryProviderHookHandle中报错：fixWebViewAsset error java.lang.NoSuchMethodException: No such accessible method: initApplicationContext() on object: org.chromium.content.app.ContentMain。 你说把file:///android_asset/wh.css 换成 file:///sdcard/xh.css是什么意思？能否说清楚点？

**Comment by dustookk** [comment]
我当时好像是把css文件的拷贝到sd卡里, 然后用 file:///sdcard/xh.css 访问的.
