### ISSUE TITLE
插件快捷方式的创建

### ISSUE THREAD

**Issue by liweiwie** [Qihoo360/DroidPlugin#24]
创建插件的快捷方式有问题呢，主程序未启动的情况下， 卡在加载界面不动了，退出，重进几次，才能好！
并且快捷方式的响应事件，是不是必须得经过主程序的跳转才行 ？

**Comment by cmzy** [comment]
是的，创建快捷方式会经过主程序的跳转。这个我已经在插件系统中有了。
