### ISSUE TITLE
怎么木有使用文档？

### ISSUE THREAD

**Issue by wingwin** [Qihoo360/DroidPlugin#32]
使用文档啊，主程序可以中止子程序么forceStopPackage  跟killApplicationProcess 这两个方法都没用啊，停不掉。。。。

**Comment by cmzy** [comment]
能否详细描述下过程？

**Comment by wywlds** [comment]
似乎是在匹配package时使用了Arrays.binarySearch,但是根据java文档，在调用Arrays.binarySearch之前需要先使用Arrays.sort排序。

**Comment by wingwin** [comment]
@cmzy 用宿主程序打开子程序后，我的子程序是一个service没有界面，这里我点击宿主的一个按钮调用forceStopPackage 或killApplicationProcess （传子程序包名）去停掉子程序，但是貌似没有用

**Comment by cmzy** [comment]
fixed  by wywlds .hahaha
