### ISSUE TITLE
请教一个问题，我按照搭建思路去搭建了，但是调用插件的时候老报错  走到这个停止Plugin Package Manager Service not be connect

### ISSUE THREAD

**Issue by xuliang271699** [Qihoo360/DroidPlugin#34]
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.droidplugin.test.main/com.droidplugin.plus.MainActivity}; have you declared this activity in your AndroidManifest.xml?
09-23 09:55:21.203 30651-30651/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
09-23 09:55:21.203 30651-30651/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
09-23 09:55:21.203 30651-30651/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3424)
09-23 09:55:21.203 30651-30651/com.droidplugin.test.main E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3385)
09-23 09:55:21.203 30651-30651/com.droidplugin.test.main E/AndroidRuntime:     at com.droidplugin.test.main.MainActivity.goPlus(MainActivity.java:53)

**Comment by cmzy** [comment]
用gralde编译，把插件中的manifest给合并到主工程中去。
