### ISSUE TITLE
导入DroidPlugin报了很多错误

### ISSUE THREAD

**Issue by Grasswolf** [Qihoo360/DroidPlugin#39]
导入DroidPlugin报了很多错误 具体错误如下
![image](https://cloud.githubusercontent.com/assets/1316918/10067063/8f536caa-62cb-11e5-997b-b90db971b212.png)

请问要编译DroidPlugin 对环境有神马要求么？

**Comment by cmzy** [comment]
编译方式问题。

**Comment by Grasswolf** [comment]
可以具体跟我说下么  该如何编译 我导入eclipse就直接报这100个错误了  还神马都没懂啊
