### ISSUE TITLE
JDK 1.6 编译失败

### ISSUE THREAD

**Issue by xueshiju** [Qihoo360/DroidPlugin#4]
由于老项目需要使用JDK1.6 出现如下两个错误。盼望解决。
Cannot cast from Object to int	MyActivityManagerService.java	
'<>' operator is not allowed for source level below 1.7	StaticProcessList.java	

![Uploading jdk16.jpg…]()

**Comment by xueshiju** [comment]
![jdk16](https://cloud.githubusercontent.com/assets/7786950/9577265/bf1f7248-5011-11e5-90ec-cf010ffc87c7.jpg)

**Comment by cmzy** [comment]
jdk最低版本必须为1.7
