### ISSUE TITLE
宿主程序由zygote64启动，而插件apk中只有armabi平台的so库。则报dlopen failed错误。

### ISSUE THREAD

**Issue by champagneguo** [Qihoo360/DroidPlugin#46]
前提：arm64位手机运行Android5.1.1操作系统，TestPlugin程序由 Zygote64启动，但是Apk插件只有armabi的so库，并能正确安装。但是在启动过程中报错。

报错：
09-21 19:34:42.751: E/art(21056): dlopen("/data/data/com.example.TestPlugin/Plugin/com.lspr/lib/libLSPR.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.example.TestPlugin/Plugin/com.lspr/lib/libLSPR.so" is 32-bit instead of 64-bit

原因：so库和宿主程序应该运行在同一平台，32位或者64位手机系统。
DroidPlugin程序出错原因，没有避免这种情况出现。经调试发现：IPluginManagerImpl.java中  private String findSoPath(Set<String> soPaths) 函数处理有问题。
 **************************************************************************************************************
private String findSoPath(Set<String> soPaths) {
		System.out.println("findSoPath:soPaths----->>>" + soPaths);
		System.out.println("findSoPath:soPaths:CPU_ABI----->>>" + Build.CPU_ABI);
		System.out.println("findSoPath:soPaths:CPU_ABI2---->>>" + Build.CPU_ABI2);
		if (soPaths != null && soPaths.size() > 0) {
			for (String soPath : soPaths) {
				if (soPath.contains(Build.CPU_ABI)) {
					System.out.println("1:ERROR:soPath:" + soPath);
					return soPath;
				}
			}
			for (String soPath : soPaths) {
				if (soPath.contains(Build.CPU_ABI2)) {
					System.out.println("2:ERROR:soPath:" + soPath);
					return soPath;
				}
			}
		}
		return null;
	}
*********************************************************************************************************************
随机加载Build.CPU_ABI2 有可能为""; 这样soPath.contains(Build.CPU_ABI2)一定为真；

Android系统是5.1.1
******************************Android.os.Build.java***********************************************************
static {
        /*
         * Adjusts CPU_ABI and CPU_ABI2 depending on whether or not a given process is 64 bit.
         * 32 bit processes will always see 32 bit ABIs in these fields for backward
         * compatibility.
         */
        final String[] abiList;
        if (VMRuntime.getRuntime().is64Bit()) {
            abiList = SUPPORTED_64_BIT_ABIS;
        } else {
            abiList = SUPPORTED_32_BIT_ABIS;
        }

        CPU_ABI = abiList[0];
        if (abiList.length > 1) {
            CPU_ABI2 = abiList[1];
        } else {
            CPU_ABI2 = "";
        }
***************************************************************************************************************
log记录
****************************************************************************************************************
09-24 20:05:16.252: I/System.out(8480): copyNativeLibs:nativeLibraryDir:/data/data/com.example.TestPlugin/Plugin/com.lspr/lib
09-24 20:05:16.252: I/System.out(8480): copyNativeLibs:apkfile:/data/data/com.example.TestPlugin/Plugin/com.lspr/apk/base-1.apk
09-24 20:05:16.254: I/System.out(8480): findSoPath:soPaths----->>>[lib/armeabi-v7a/libLSPR.so, lib/armeabi/libLSPR.so]
09-24 20:05:16.254: I/System.out(8480): findSoPath:soPaths:CPU_ABI----->>>arm64-v8a
09-24 20:05:16.254: I/System.out(8480): findSoPath:soPaths:CPU_ABI2---->>>
09-24 20:05:16.254: I/System.out(8480): 2:ERROR:soPath:lib/armeabi-v7a/libLSPR.so
09-24 20:05:16.254: I/System.out(8480): return soPath:lib/armeabi-v7a/libLSPR.so
09-24 20:05:16.254: I/System.out(8480): copyNativeLibs:file:-->>/data/data/com.example.TestPlugin/Plugin/com.lspr/lib/libLSPR.so
*****************************************************************************************************************

**Comment by cmzy** [comment]
fixed
