### ISSUE TITLE
在主activity中调用installPackage返回-1

### ISSUE THREAD

**Issue by Grasswolf** [Qihoo360/DroidPlugin#47]
我manifest文件如下：

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:name="com.morgoo.droidplugin.PluginApplication">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

主activity代码如下：
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        String pluginSrcDir = sdcard + "/Download/SimpleGame.apk";

        if (fileIsExists(pluginSrcDir)) {
            try {
                PluginManager.getInstance().installPackage(pluginSrcDir, 0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            startMainActivity();
        }
    }

然后我跟代码的时候发现 在调用installPackage的时候 应为这个时候PluginManager的onServiceConnected还没有返回从而mPluginManager值还是为null 导致installPackage返回-1，

但是我加上PluginManager.getInstance().waitForConnected();的话 程序又会卡死 这个该如何避免啊

**Comment by cmzy** [comment]
用gradle，合并manifest！

**Comment by Grasswolf** [comment]
不是啊，服务是能连上的onServiceConnected也是会返回的 只是我在调用installPackage的时候他还没有返回而已，如果我弄个按钮，点击按钮再去installPackage那是可以成功的 所以这个应该跟和合并manifest没有关系吧，还是我使用的方法不对

**Comment by simplehappy2600** [comment]
eclipse工程 project.properties 中加 manifestmerger.enabled=true,  installPackage ok

**Comment by Kinka** [comment]
应该就是加载先后顺序的问题，onCreate中直接调用installPackage的时候还没有onServiceConnected, mPluginManager这个对象还没有初始化，所以失败返回-1。另外，如果已安装过该apk而传入flags的值为0,那么也是会返回-1, 把flags改为PackageManagerCompat.INSTALL_REPLACE_EXISTING即可。

**Comment by zhc81972335** [comment]
我也遇到类似问题，我的android版本是16，所以框架中BundleCompat这个类有问题，
static {
        if (Build.VERSION.SDK_INT < 18) {
            try {
                getIBinder = Bundle.class.getDeclaredMethod("getIBinder", String.class);
            } catch (NoSuchMethodException e) {
                //ignore
            }
            try {
                putIBinder = Bundle.class.getDeclaredMethod("getIBinder", String.class, IBinder.class);
            } catch (NoSuchMethodException e) {
                //ignore
            }
        }
    }
putIBinder = Bundle.class.getDeclaredMethod("getIBinder", String.class, IBinder.class);这个反射方法有问题，方法名写错了，方法名应该是putIBinder
