### ISSUE TITLE
应用重复启动问题怎么解决啊？

### ISSUE THREAD

**Issue by zhengnt** [Qihoo360/DroidPlugin#50]
插件与插件，插件与宿主之间的互相调用会导致应用（或者页面）的重复启动，使用各种lanuchMode和flag都无效，不知道要怎么实现单例？

**Comment by cmzy** [comment]
这是目前我们的一个bug。对launchmode支持不好。所有的launchmode都被转换为standard模式。

**Comment by cmzy** [comment]
fixed.请更新代码后重试。

**Comment by zhengnt** [comment]
赞一个！牛掰啊，文档记得修改哦！
