### ISSUE TITLE
关于使用自定义的Application

### ISSUE THREAD

**Issue by newstart201212** [Qihoo360/DroidPlugin#52]
我遇到了一个问题: 在使用自定义的application时候, 应用启动总是失败,我就在TestPlugin里加入了自己的applicaition类, 
public class MyApplication extends Application {
    
    @Override
    public void onCreate() {
        super.onCreate();
        PluginHelper.getInstance().applicationOnCreate(getBaseContext());

    }

    @Override
    protected void attachBaseContext(Context base) {
        PluginHelper.getInstance().applicationAttachBaseContext(base);
    }

    
}
, manifest里改成:
<application android:name="com.example.TestPlugin.MyApplication" android:label="@string/app_name"
                 android:icon="@drawable/ic_launcher" android:theme="@style/AppTheme">

下面是log, 也查看了ContextWrapper.java, 发现mBase为空.
      public PackageManager getPackageManager() {
         return mBase.getPackageManager();
      }
 
10-10 19:21:28.358 E/AndroidRuntime(18538): FATAL EXCEPTION: main
10-10 19:21:28.358 E/AndroidRuntime(18538): Process: com.example.TestPlugin, PID: 18538
10-10 19:21:28.358 E/AndroidRuntime(18538): java.lang.NullPointerException
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.content.ContextWrapper.getPackageName(ContextWrapper.java:135)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4784)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4413)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4353)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.os.Looper.loop(Looper.java:136)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-10 19:21:28.358 E/AndroidRuntime(18538): 	at dalvik.system.NativeStart.main(Native Method)
10-10 19:21:28.358 W/ActivityManager( 1168):   Force finishing activity com.example.TestPlugin/.MyActivity

**Comment by cmzy** [comment]
把这一行去掉呢？  PluginHelper.getInstance().applicationAttachBaseContext(base);

**Comment by newstart201212** [comment]
试过了, 还是一样的.你能发个好用的例子不?

**Comment by cmzy** [comment]
PluginApplication就是一个例子啊。我看你写的没问题啊。

manifest里改成:
android:icon="@drawable/ic_launcher" android:theme="@style/AppTheme">是哪一个的manifest?droid plugin里面的？

**Comment by newstart201212** [comment]
manifest 是我应用程序的,

**Comment by newstart201212** [comment]
manifest是我应用程序的, 不是droidPlugin的, 只是想说这里没有引用插件的com.morgoo.droidplugin.PluginApplication.
关于例子, 能不能给个类似于你下载包里的TestPlugin(把DroidPlugin当做lib使用的), 然后manifest里声明自己的application, 同时还能PluginManager功能的, eg.PluginManager.getInstance().deletePackage()

**Comment by newstart201212** [comment]
@cmzy,
问题解决了, 我重新看了一个DroidPlugin的applicaiton,
    @Override
    protected void attachBaseContext(Context base) {
        PluginHelper.getInstance().applicationAttachBaseContext(base);
        super.attachBaseContext(base);  //这句忘记了, 当然不会加载...., ps. 你的中文文档里也没没写这个, 有时间更新一下吧
    }
谢了.

**Comment by cmzy** [comment]
fixed
