### ISSUE TITLE
Android 6.0 白屏

### ISSUE THREAD

**Issue by aesean** [Qihoo360/DroidPlugin#53]
Nexus5，Android6.0白屏。

**Comment by cmzy** [comment]
请给一个日志。。

**Comment by JackCho** [comment]
遇到同样的问题，不过是在sony z2、rom 4.4.4。跳转到已安装插件不成功，卡在“努力加载中...”这个页面 
@cmzy 没有什么日志输出

**Comment by cmzy** [comment]
@JackCho 请问你装上360手机助手试试是否会卡住呢？参考呢faq的内容了吗？

**Comment by JackCho** [comment]
我的问题找到root cause了，是stub process启动的时候，没有在Application里面做`PluginHelper.getInstance().applicationOnCreate(getBaseContext());`
在此留言，希望可以帮助到大家

**Comment by cmzy** [comment]
close
