### ISSUE TITLE
宿主和插件各有一个activity, 首次启动插件的activity时候会弹出一个白屏"努力加载中.."

### ISSUE THREAD

**Issue by newstart201212** [Qihoo360/DroidPlugin#54]
启动了ActivityStub$StandardP02, 白屏,显示"努力加载中"...., 怎么去掉这一屏啊?

10-14 18:31:31.872 E/Learn_MainActivity(22493): ===========onCreate()===========
10-14 18:31:31.872 D/Learn_MainActivity(22493): onCreate()
10-14 18:31:31.892 I/Timeline(22493): Timeline: Activity_launch_request id:com.example.TestPlugin time:1098757655
10-14 18:31:31.892 I/ThermalEngine(  383): Sensor:batt_temp:369 mC
10-14 18:31:31.892 I/ActivityManager( 1168): START u0 {cmp=com.example.TestPlugin/com.morgoo.droidplugin.stub.ActivityStub$StandardP02 (has extras)} from pid 22493
10-14 18:31:31.902 V/PhoneStatusBar( 1270): setLightsOn(true)
10-14 18:31:31.912 I/Learn_MainActivity(22493): onResume()
10-14 18:31:31.962 V/CameraServiceListener(22493): Camera id 0 has status changed to 0x1
10-14 18:31:31.962 V/CameraServiceListener(22493): Camera id 1 has status changed to 0x1
10-14 18:31:31.972 D/Learn_Activity2(22493): Activity2 onCreate()
10-14 18:31:31.972 I/Learn_Activity2(22493): onResume()
10-14 18:31:32.012 I/Adreno-EGL(22493): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
10-14 18:31:32.012 I/Adreno-EGL(22493): OpenGL ES Shader Compiler Version: E031.24.00.15
10-14 18:31:32.012 I/Adreno-EGL(22493): Build Date: 04/07/15 Tue
10-14 18:31:32.012 I/Adreno-EGL(22493): Local Branch: 
10-14 18:31:32.012 I/Adreno-EGL(22493): Remote Branch: 
10-14 18:31:32.012 I/Adreno-EGL(22493): Local Patches: 
10-14 18:31:32.012 I/Adreno-EGL(22493): Reconstruct Branch: 
10-14 18:31:32.052 D/OpenGLRenderer(22493): Enabling debug mode 0
10-14 18:31:32.072 D/AppOps  ( 1168): checkOperation :code 24 uid 10306 package com.baidu.input
10-14 18:31:32.102 I/Timeline(22493): Timeline: Activity_idle id: android.os.BinderProxy@431aad20 time:1098757867
10-14 18:31:32.102 I/Timeline(22493): Timeline: Activity_idle id: android.os.BinderProxy@42f52e50 time:1098757867
10-14 18:31:32.122 I/ActivityManager( 1168): Displayed com.example.TestPlugin/com.morgoo.droidplugin.stub.ActivityStub$StandardP02: +194ms (total +573ms)

**Comment by cmzy** [comment]
没明白，为什么要去掉？

**Comment by newstart201212** [comment]
我没说清楚，有个宿主A,要启动它的插件B。在A的activity里安装插然后件启B,然后启动B的入口activity,结果在显示B的activity之前会弹出一个白屏界面，显示努力加载中，查了log知道是droidplugin的activitystu,b,怎么能去掉这屏？附上log.
另外，是不是用pluginmanager install一个未安装的插件后，想调用service,activity都可以用android标准用法？

**Comment by rockswang** [comment]
请问"努力加载中"这个字符串是定义在哪里的？如何修改？

**Comment by rockswang** [comment]
努力加载中是Theme中的windowBackground，是Plugin项目里面的一张图片，我找了半天字符串也没找到，汗了

**Comment by levianye** [comment]
和我遇到的问题一样，就是想问下如何快速的finish掉这个中间的stub activity，因为实在是和前面的host的activity以及后面的插件activity太不协调了，如果设置这个stub activity为透明又会让用户感觉特别卡，没反应，这个activity会占用3-5秒的时间，也就是点击后有这么3-5秒看起来还是没有反应的，有什么好的办法优化这个么？

**Comment by Wmmeng** [comment]
这个问题已经有人提了，修改下PluginManager的STUB_AUTHORITY_NAME跟你在provider提供的authrity一致就行了。
