### ISSUE TITLE
加载了droidPlugin的宿主,在启动一个未安装的插件的service时, 首次启动失败

### ISSUE THREAD

**Issue by newstart201212** [Qihoo360/DroidPlugin#55]
宿主里启动未安装的插件service(AndroidManifest里声明exported=true), 没反应.
第2次以后才可以启动.

具体过程:
1. 插件里有个service,
2. 宿主在PluginManager.getInstance().isConnected()之后查询插件, 
    然后PluginManager.getInstance().installPackage(), 
    之后要启动插件的service, 此时service没被启动, 
		Intent it = new Intent();
		it.setClassName("com.example.test2", "com.example.test2.Test2Service");
		mContext.startService(it);
3. 再重复上面操作, 可以启动插件service

**Comment by cmzy** [comment]
安装失败了吧？安装完成后需要检测一下插件是否安装成功。
