### ISSUE TITLE
在宿主中反射子插件的Fragment为空，求大神回复啊

### ISSUE THREAD

**Issue by SunnyBoolean** [Qihoo360/DroidPlugin#64]
问题是这样的，我的宿主程序有几个插件，每个插件的入口是Fragment，我在宿主中通过反射获取Fragment一直是null啊，求解怎么破？反射我直接使用Class.forName("com.......Fragment")来的，求回复啊。。

**Comment by cmzy** [comment]
目前还不支持这种方式，后续我们会支持的。

**Comment by cmzy** [comment]
目前还不支持这种方式，后续我们会支持的。

**Comment by rockswang** [comment]
不是一个进程吧，没法反射吧

**Comment by geniusmart** [comment]
@cmzy实现的思路是否可以先透露下

**Comment by tiann** [comment]
插件和宿主都不是运行在一个进程，咋个反射法？
