### ISSUE TITLE
TestPlugin安装不了

### ISSUE THREAD

**Issue by moyaying** [Qihoo360/DroidPlugin#65]
Installing com.example.TestPlugin
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.example.TestPlugin"
	pkg: /data/local/tmp/com.example.TestPlugin
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]

**Comment by rockswang** [comment]
因为在360手机助手里面用了这个插件库，因此用默认的authorities会导致冲突，需要按照文档里面的修改每个provider的authorities即可，另外，PluginManager.STUB_AUTHORITY_NAME好像也需要一起改一下

**Comment by moyaying** [comment]
IC, 谢了
