### ISSUE TITLE
问个问题，我测试是已经通过了，但是插件开发中，安装后，调用的时候出错

### ISSUE THREAD

**Issue by xuliang271699** [Qihoo360/DroidPlugin#68]
java.lang.SecurityException:
AndroidRuntime: java.lang.SecurityException: Invalid mkdirs path: /storage/sdcard1/Android/data/com.careerforce.mianshi.shangji_ms_main/cache/
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1474)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1427)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at android.os.storage.IMountService$Stub$Proxy.mkdirs(IMountService.java:783)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:51)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at com.morgoo.droidplugin.hook.binder.BinderHook.invoke(BinderHook.java:57)
11-05 16:05:00.856 19641-19641/com.careerforce.mianshi:PluginP02 E/AndroidRuntime:     at com.morgoo.droidplugin.hook.binder.IMountServiceBinder.invoke(IMountServiceBinder.java:34)

**Comment by cmzy** [comment]
这是已知bug，已经fix，稍后会提交代码。
