### ISSUE TITLE
demo安装饿了么(5.4)失败

### ISSUE THREAD

**Issue by furutuki** [Qihoo360/DroidPlugin#71]
弹出toast提示”安装失败，文件请求的权限太多“

**Comment by aiplay** [comment]
我试了很多应用也遇到同样的问题，是不是需要在TestPlugin的AndroidManifest里添加插件所需的权限？

**Comment by yarkey09** [comment]
在AndroidManifest.xml中必须把所有插件中需要用到的 权限都声明了才行

**Comment by swustmuzi** [comment]
声明了也还是报错啊.给的TestPlugin工程是没有声明权限的,但是有些应用也能安装上,有哪位大神回答一下吗?

**Comment by swustmuzi** [comment]
应该是非android的权限以及系统级的权限需要在host里面声明
