### ISSUE TITLE
DroidPlugin在64位CPU上运行包含有非64位.so包的应用失败，直接安装该包可以运行

### ISSUE THREAD

**Issue by 455586841** [Qihoo360/DroidPlugin#74]
我有一个百度地图的工程，在其他手机上运行正常（指的是DroidPlugin插件安装方式），但在小米4c上，只要运行包含地图的页面，就卡死、黑频、无响应。经过多发验证，发现，百度地图3.4及以前版本，没有对64位做支持的，故而在安装的插件（Plugin/xxx.xxx.xxx/lib）下，没有该有的so文件，即使是拷贝过去，也不能运行；但是我直接在小米4c上安装该应用，是可以运行的；

另外，建议DroidPlugin对安装插件运行崩溃做出检测，以防插件崩溃，整个应用黑屏、卡死、无响应。

**Comment by 455586841** [comment]
附上错误日志：
11-16 09:59:02.038 375-375/? E/qdhwcomposer: setRefreshRate: Failed to write 60 with error Operation not permitted
11-16 09:59:02.048 15201-15201/? E/art: No implementation found for boolean com.baidu.platform.comjni.engine.JNIEngine.InitEngine(android.content.Context, android.os.Bundle) (tried Java_com_baidu_platform_comjni_engine_JNIEngine_InitEngine and Java_com_baidu_platform_comjni_engine_JNIEngine_InitEngine__Landroid_content_Context_2Landroid_os_Bundle_2)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler: Thread[main,5,main]
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler: {"versionName":"2.4.6","versionCode":25,"osVersion":"5.1.1","sdkVersion":"22","phoneType":"Mi-4c","brand":"Xiaomi","memoryTotal":"-1264.65MB","manufacturer":"Xiaomi","wifiMac":"20:82:c0:6d:bc:a8","systemRealtime":"2天57小时28分","CPU_ABI":"arm64-v8a","CPU_ABI2":"","widthPixels":1080,"heightPixels":1920,"xdpi":449.7040100097656,"ydpi":447.4119873046875,"densityDpi":480,"density":3,"scaledDensity":3}
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tydic.iem.sc/com.tydic.iem.activity.SignActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.baidu.mapapi.map.MapView
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.access$800(ActivityThread.java:154)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Looper.loop(Looper.java:135)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.main(ActivityThread.java:5275)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Native Method)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Method.java:372)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:  Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class com.baidu.mapapi.map.MapView
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createView(LayoutInflater.java:637)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.setContentView(Activity.java:2175)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.vutils.core.view.layer.VUActivity.setContentView(VUActivity.java:15)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.tydic.iem.activity.SignActivity.onCreate(SignActivity.java:84)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.performCreate(Activity.java:6051)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:92)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Looper.loop(Looper.java:135) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.main(ActivityThread.java:5275) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:  Caused by: java.lang.reflect.InvocationTargetException
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Constructor.newInstance(Native Method)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createView(LayoutInflater.java:611)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.setContentView(Activity.java:2175) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.vutils.core.view.layer.VUActivity.setContentView(VUActivity.java:15) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.tydic.iem.activity.SignActivity.onCreate(SignActivity.java:84) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.performCreate(Activity.java:6051) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:92) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Looper.loop(Looper.java:135) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.main(ActivityThread.java:5275) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:  Caused by: java.lang.UnsatisfiedLinkError: No implementation found for boolean com.baidu.platform.comjni.engine.JNIEngine.InitEngine(android.content.Context, android.os.Bundle) (tried Java_com_baidu_platform_comjni_engine_JNIEngine_InitEngine and Java_com_baidu_platform_comjni_engine_JNIEngine_InitEngine__Landroid_content_Context_2Landroid_os_Bundle_2)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.baidu.platform.comjni.engine.JNIEngine.InitEngine(Native Method)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.baidu.platform.comjni.engine.AppEngine.InitEngine(Unknown Source)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.baidu.mapapi.a.b(Unknown Source)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.baidu.mapapi.map.MapView.a(Unknown Source)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.baidu.mapapi.map.MapView.<init>(Unknown Source)
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Constructor.newInstance(Native Method) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.setContentView(Activity.java:2175) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.vutils.core.view.layer.VUActivity.setContentView(VUActivity.java:15) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.tydic.iem.activity.SignActivity.onCreate(SignActivity.java:84) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Activity.performCreate(Activity.java:6051) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:92) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.os.Looper.loop(Looper.java:135) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at android.app.ActivityThread.main(ActivityThread.java:5275) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
11-16 09:59:02.048 15201-15201/? E/VUExceptionAndCrashHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by cmzy** [comment]
请参照：https://github.com/Qihoo360/DroidPlugin/commit/534a970440ff149f369f5a11611b191523a0ebe7
