### ISSUE TITLE
运行内涵段子[糗事百科]apk崩溃

### ISSUE THREAD

**Issue by leafzz** [Qihoo360/DroidPlugin#78]
最新代码运行内涵段子apk，进入主界面过一会就崩溃了。
ps: 我邮件有发给你具体的截图和log文件，by 409213623@qq.com

崩溃日志如下：
11-20 18:52:50.349 12137-12137/com.example.TestPlugin D/FeatureProxyBase: FeatureProxyBase class constructor
11-20 18:52:50.349 12137-12137/com.example.TestPlugin D/MultiWindow: MultiWindowProxy constructor.
11-20 18:52:50.349 12137-12137/com.example.TestPlugin D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
11-20 18:52:50.444 12137-12137/com.example.TestPlugin D/AbsListView: reportScrollStateChange: newState = 0, mLastScrollState = 0, mOnScrollListener = null, mScrollY = 0, mTouchMode = -1, mFirstPosition = 0
11-20 18:52:50.483 12137-12137/com.example.TestPlugin D/FeatureProxyBase: FeatureProxyBase class constructor
11-20 18:52:50.483 12137-12137/com.example.TestPlugin D/MultiWindow: MultiWindowProxy constructor.
11-20 18:52:50.483 12137-12137/com.example.TestPlugin D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
11-20 18:52:50.571 12137-12137/com.example.TestPlugin D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}}
11-20 18:52:50.655 12137-12137/com.example.TestPlugin D/ActivityThread: ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@23150d68
11-20 18:52:50.666 12137-12137/com.example.TestPlugin D/AbsListView: onWindowFocusChanged: hasWindowFocus=false, this=android.widget.ListView{1060636 VFED.VC. ......I. 0,0-720,1070 #102000a android:id/list}
11-20 18:52:50.667 12137-12137/com.example.TestPlugin D/AbsListView: onWindowFocusChanged: hasWindowFocus=false, this=android.widget.ListView{3953184b VFED.VC. ......ID 0,0-720,1070 #102000a android:id/list}
11-20 18:52:50.723 12137-12137/com.example.TestPlugin D/Surface: Surface::disconnect(this=0x7f7c642600,api=2)
11-20 18:52:50.723 12137-12137/com.example.TestPlugin D/GraphicBuffer: unregister, handle(0x7f72972100) (w:720 h:1280 s:720 f:0x2 u:0x000933)
11-20 18:52:50.724 12137-12137/com.example.TestPlugin D/GraphicBuffer: unregister, handle(0x7f729722e0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
11-20 18:52:50.729 12137-12137/com.example.TestPlugin D/GraphicBuffer: unregister, handle(0x7f729721a0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
11-20 18:52:51.207 12137-12137/com.example.TestPlugin D/ActivityThread: SVC-Calling onStartCommand: com.morgoo.droidplugin.PluginManagerService@1d850450, flags=0, startId=8
11-20 18:52:51.208 12137-12137/com.example.TestPlugin D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@3ab7ca13 startId=8 args=Intent { pkg=com.example.TestPlugin cmp=com.example.TestPlugin/com.morgoo.droidplugin.PluginManagerService }}
11-20 18:52:56.112 12137-12137/com.example.TestPlugin V/ActivityThread: Finishing stop of ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}}: show=false win=com.android.internal.policy.impl.PhoneWindow@3d14b506
11-20 18:52:56.113 12137-12137/com.example.TestPlugin V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{2d245fe0 com.example.TestPlugin/com.example.TestPlugin.MyActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3bdc08bd I.E..... R.....I. 0,0-720,1280}
11-20 18:52:56.113 12137-12137/com.example.TestPlugin D/ActivityThread: ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@23150d68
11-20 18:52:59.189 12137-12137/com.example.TestPlugin V/ActivityThread: Performing resume of ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}}
11-20 18:52:59.198 12137-12137/com.example.TestPlugin D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}}
11-20 18:52:59.198 12137-12137/com.example.TestPlugin V/ActivityThread: Resume ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}} started activity: false, hideForNow: false, finished: false
11-20 18:52:59.198 12137-12137/com.example.TestPlugin V/ActivityThread: Resuming ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}} with isForward=false
11-20 18:52:59.200 12137-12137/com.example.TestPlugin D/FeatureProxyBase: FeatureProxyBase class constructor
11-20 18:52:59.200 12137-12137/com.example.TestPlugin D/MultiWindow: MultiWindowProxy constructor.
11-20 18:52:59.200 12137-12137/com.example.TestPlugin D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
11-20 18:52:59.203 12137-12137/com.example.TestPlugin V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{2d245fe0 com.example.TestPlugin/com.example.TestPlugin.MyActivity,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3bdc08bd V.E..... R.....ID 0,0-720,1280}
11-20 18:52:59.204 12137-12137/com.example.TestPlugin V/ActivityThread: Scheduling idle handler for ActivityRecord{73c688b token=android.os.BinderProxy@23150d68 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}}
11-20 18:52:59.206 12137-12137/com.example.TestPlugin D/ActivityThread: ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@23150d68
11-20 18:52:59.233 12137-12137/com.example.TestPlugin D/ListView: mSelectorRect.setEmpty in layoutChildren this=android.widget.ListView{1060636 VFED.VC. .F....ID 0,0-720,1070 #102000a android:id/list}
11-20 18:52:59.234 12137-12137/com.example.TestPlugin D/Surface: Surface::connect(this=0x7f7c642600,api=2)
11-20 18:52:59.240 12137-12137/com.example.TestPlugin D/GraphicBuffer: register, handle(0x7f729ba980) (w:720 h:1280 s:720 f:0x2 u:0x000933)
11-20 18:53:00.428 12137-12137/com.example.TestPlugin D/GraphicBuffer: register, handle(0x7f729721a0) (w:720 h:1280 s:720 f:0x2 u:0x000933)
11-20 18:53:00.445 12137-12137/com.example.TestPlugin D/GraphicBuffer: register, handle(0x7f729722e0) (w:720 h:1280 s:720 f:0x2 u:0x000933)

**Comment by cmzy** [comment]
没崩溃信息啊

**Comment by leafzz** [comment]
你们的日志就是打出这些信息
直接整个进程崩溃了

而且安装360手机助手也 一直提示 X应用未安装

**Comment by leafzz** [comment]
我把具体的信息和截图 发你邮箱，你看看，这里不知道怎样上传

**Comment by leafzz** [comment]
呃，，我邮件有发过给你的

**Comment by leafzz** [comment]
我觉得你们还是买一部这个手机 去测试一下
