### ISSUE TITLE
把provider修改成自己的以后，每次打开插件，第一次总会卡在努力加载中...第二次进去则是好的。请问怎么处理啊

### ISSUE THREAD

**Issue by helloxuetao** [Qihoo360/DroidPlugin#79]

**Comment by newstart201212** [comment]
我也遇到这个问题了, 你看res里有个.9图片, 删了就好了

**Comment by motcwang** [comment]
为什么删了.9 图片就可以了？

**Comment by motcwang** [comment]
我删了.9 效果是一样的，并不好用

**Comment by rockswang** [comment]
请参考 #80

**Comment by codehz** [comment]
你有没有仔细看文档，这个问题已经被很多人问了很多遍了（我是第一个问的 #3  ）然后开发者早就给出了解决方法，修改PluginManager.STUB_AUTHORITY_NAME常量为你修改后的提供者名字。。。。

**Comment by Wmmeng** [comment]
我也遇到了这个问题，修改后亲测可运行
