### ISSUE TITLE
特性请求：增加应用能够自己控制使用那个预定义的activity作为目标activity的StubActivity能力

### ISSUE THREAD

**Issue by luoqii** [Qihoo360/DroidPlugin#82]
我的插件有多个activity，他们必须是sigleInstance模式才能符合产品需求，
这种情况下，就需要提供一种机制，让应用能够控制这部分逻辑；service,
亦是如此。

**Comment by cmzy** [comment]
已经支持sigleInstance了。

**Comment by luoqii** [comment]
我更新了代码，看到已经支持4个这种模式的activity，问题来了：
如果要支持5个涅？6个。。。 17个？（我的插件需要8个这样的
activity,不要笑我，不是我加的)

所以是不是这一机制还是需要的？
以不变应万变

**Comment by cmzy** [comment]
理论上都支持。

**Comment by luoqii** [comment]
i know 

那是否有这样的计划尼？
相信其他开发者也有这样的需求，
或者你有更好，更灵活的方案？

**Comment by cmzy** [comment]
没有这样的计划。原因在于，Activity分配有插件系统自动分配，这有一个比较复杂的调度过程，如果交由开发者具体去做的话会导致更多的未知问题。当然，如果愿意，你可以在遵守我们开源协议(LGPL)的前提下，自己修改。

**Comment by luoqii** [comment]
对应的Stub activity是手工编辑的，还是脚步控制的？
我想增加几个signleinstance模式的activity.该怎么做呢？

**Comment by cmzy** [comment]
手工编辑。
