### ISSUE TITLE
TestPlugin无法安装真机上

### ISSUE THREAD

**Issue by aiplay** [Qihoo360/DroidPlugin#86]
使用android studio打包安装TestPlugin项目，一直提示安装失败，试了好几个手机都这样。
错误信息如下：
Target device: xiaomi-hm_1s-708b5977
Installing APK: /Users/xujh/open/DroidPlugin/project/TestPlugin/bin/outputs/apk/TestPlugin-debug.apk
Uploading file to: /data/local/tmp/com.example.TestPlugin
Installing com.example.TestPlugin
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.example.TestPlugin"
open: Permission denied
open: Permission denied
	pkg: /data/local/tmp/com.example.TestPlugin
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]

DEVICE SHELL COMMAND: pm uninstall com.example.TestPlugin
Unknown failure (Failure)

**Comment by cmzy** [comment]
see readme.md
