### ISSUE TITLE
插件更新问题：

### ISSUE THREAD

**Issue by sqc0720** [Qihoo360/DroidPlugin#94]
目录下有两个不同版本的apk 我点击安装老的版本apk，在待安装界面这两个apk 的状态都是已安装状态，但是进去这个apk 显示的是老版的APK， 我看文档中flags 参数为PackageManagerCompat.INSTALL_REPLACE_EXISTING，即可，但是我这面没有达到预期效果

**Comment by cmzy** [comment]
那只是一个演示程序，为了演示如何启动安装插件，具体使用需要集成后再通过API用。
