### ISSUE TITLE
安装的应用程序没有区分版本

### ISSUE THREAD

**Issue by yarkey09** [Qihoo360/DroidPlugin#95]
我在sdcard/目录下放了同个应用的不同版本apk，比如：test_v1.0.apk, test_v1.1.apk, test_v1.2.apk，包名都是一样的（同一个应用的不同版本而已）。
这个时候我安装任意一个版本，都会显示 三个版本都已经安装。而不会显示只安装了其中一个版本。

**Comment by cmzy** [comment]
这是测试程序的问题，确实没区分，但是并不影响插件系统本身，所以先不改。
