### ISSUE TITLE
android.util.Singleton cannot be resolved to a type

### ISSUE THREAD

**Issue by ewang1986** [Qihoo360/DroidPlugin#98]
什么问题？

**Comment by ZhiZunBao-** [comment]
我也遇到同样的问题 ，编译版本为22的时候，找不到android.util.Singleton

**Comment by tianqiujie** [comment]
lib文件夹里面jar文件你要放到libs里面或者build path里面引用就可以了


2015-12-24 11:00 GMT+08:00 ZhiZunBao- <notifications@github.com>:
